import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../data_service.dart';
import '../models/camera_model.dart';
import 'roi_painter.dart';

class ImageDrawingCanvas extends StatefulWidget {
  final Camera camera;

  const ImageDrawingCanvas({super.key, required this.camera});

  @override
  State<ImageDrawingCanvas> createState() => _ImageDrawingCanvasState();
}

class _ImageDrawingCanvasState extends State<ImageDrawingCanvas> {
  // State for drawing
  List<Point> _currentPoints = [];
  bool _isDrawing = false;
  String _selectedType = 'road'; // Default type
  final TextEditingController _labelController = TextEditingController();
  
  @override
  void didUpdateWidget(ImageDrawingCanvas oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.camera.id != widget.camera.id) {
       _currentPoints.clear();
       _isDrawing = false;
    }
  }

  void _addPoint(TapUpDetails details, BoxConstraints constraints) {
    if (!_isDrawing) {
      setState(() {
        _isDrawing = true;
        _currentPoints.clear();
      });
    }

    // Normalize coordinates (0-1)
    final double x = details.localPosition.dx / constraints.maxWidth;
    final double y = details.localPosition.dy / constraints.maxHeight;

    setState(() {
      _currentPoints.add(Point(x: x, y: y));
    });
  }

  void _undoLastPoint() {
    if (_currentPoints.isNotEmpty) {
      setState(() {
        _currentPoints.removeLast();
        if (_currentPoints.isEmpty) {
          _isDrawing = false;
        }
      });
    }
  }

  void _finishPolygon() {
    if (_currentPoints.length < 3) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Polygon needs at least 3 points!')),
      );
      return;
    }

    _showLabelDialog();
  }

  void _showLabelDialog() {
    _labelController.clear();
    showDialog(
      context: context,
      builder: (_) => AlertDialog(
        title: const Text('Name this ROI'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(controller: _labelController, decoration: const InputDecoration(labelText: 'ROI Label')),
            const SizedBox(height: 16),
            DropdownButton<String>(
              value: _selectedType,
              isExpanded: true,
              items: const [
                DropdownMenuItem(value: 'road', child: Text('Road (Blue)')),
                DropdownMenuItem(value: 'garbage', child: Text('Garbage (Green)')),
                DropdownMenuItem(value: 'streetlight', child: Text('Streetlight (Yellow)')),
                DropdownMenuItem(value: 'pothole', child: Text('Pothole (Red)')),
                DropdownMenuItem(value: 'overflow', child: Text('Drainage Overflow (Brown)')),
                DropdownMenuItem(value: 'waterleak', child: Text('Water Leak (Cyan)')),
                DropdownMenuItem(value: 'roadcrack', child: Text('Road Crack (Purple)')),
              ],
              onChanged: (val) {
                if (val != null) setState(() => _selectedType = val);
                // Navigator.pop(context); // Don't close dialog on selection, let user type name
                // _showLabelDialog(); 
              }, 
            ),
          ],
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
          ElevatedButton(
            onPressed: () {
              if (_labelController.text.isNotEmpty) {
                 _addRegion(_labelController.text);
                 Navigator.pop(context);
              }
            },
            child: const Text('Save ROI'),
          ),
        ],
      ),
    );
  }

  Future<void> _addRegion(String label) async {
    final newRegion = RegionOfInterest(
      id: '', // Generated by Firestore
      label: label,
      type: _selectedType,
      points: List.from(_currentPoints),
    );

    setState(() {
      _currentPoints.clear();
      _isDrawing = false;
    });

    try {
      await Provider.of<DataService>(context, listen: false).addRegion(widget.camera.id, newRegion);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Region added!')));
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error adding region: $e')));
      }
    }
  }

  Future<void> _deleteRegion(String id) async {
    try {
      await Provider.of<DataService>(context, listen: false).deleteRegion(widget.camera.id, id);
       if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Region deleted!')));
      }
    } catch (e) {
       if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error deleting region: $e')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        // Toolbar
        Container(
          padding: const EdgeInsets.all(8),
          color: Colors.grey.shade100,
          child: Row(
            children: [
              const Text('Drawing Tool', style: TextStyle(fontWeight: FontWeight.bold)),
              const SizedBox(width: 16),
              const Text('Type:'),
              const SizedBox(width: 8),
              DropdownButton<String>(
                value: _selectedType,
                items: const [
                  DropdownMenuItem(value: 'road', child: Text('Road')),
                  DropdownMenuItem(value: 'garbage', child: Text('Garbage')),
                  DropdownMenuItem(value: 'streetlight', child: Text('Streetlight')),
                  DropdownMenuItem(value: 'pothole', child: Text('Pothole')),
                  DropdownMenuItem(value: 'overflow', child: Text('Overflow')),
                  DropdownMenuItem(value: 'waterleak', child: Text('Water Leak')),
                  DropdownMenuItem(value: 'roadcrack', child: Text('Road Crack')),
                ],
                onChanged: (val) => setState(() => _selectedType = val!),
              ),
              const Spacer(),
              ElevatedButton.icon(
                onPressed: (_isDrawing && _currentPoints.isNotEmpty) ? _undoLastPoint : null,
                icon: const Icon(Icons.undo),
                label: const Text('Undo'),
                style: ElevatedButton.styleFrom(backgroundColor: Colors.orange, foregroundColor: Colors.white),
              ),
              const SizedBox(width: 8),
              ElevatedButton.icon(
                onPressed: _isDrawing ? () => setState(() { _isDrawing = false; _currentPoints.clear(); }) : null,
                icon: const Icon(Icons.cancel),
                label: const Text('Cancel'),
                style: ElevatedButton.styleFrom(backgroundColor: Colors.grey, foregroundColor: Colors.white),
              ),
            ],
          ),
        ),

        // Canvas Area
        Expanded(
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
               // The Image Canvas
               Expanded(
                 flex: 3,
                 child: Container(
                   margin: const EdgeInsets.all(16),
                   decoration: BoxDecoration(
                     border: Border.all(color: Colors.grey),
                   ),
                   child: LayoutBuilder(
                     builder: (context, constraints) {
                       return GestureDetector(
                         onTapUp: (details) => _addPoint(details, constraints),
                         onDoubleTap: _finishPolygon,
                         child: Stack(
                           fit: StackFit.expand,
                           children: [
                             // Background Image
                             if (widget.camera.snapshotUrl.isNotEmpty)
                               Image.network(
                                 widget.camera.snapshotUrl,
                                 fit: BoxFit.fill, 
                                 errorBuilder: (_, __, ___) => const Center(child: Icon(Icons.broken_image)),
                               )
                             else
                               const Center(child: Text('No Image')),
                             
                             // Custom Painter
                             CustomPaint(
                               painter: RoiPainter(
                                 regions: widget.camera.regions, // Use camera regions directly
                                 currentPoints: _currentPoints,
                                 currentType: _selectedType,
                               ),
                               size: Size(constraints.maxWidth, constraints.maxHeight),
                              ),
                             
                             // Instructions overlay
                             if (!_isDrawing && widget.camera.regions.isEmpty)
                               const Center(
                                 child: IgnorePointer(
                                   child: Text(
                                     'Tap to start drawing polygon.\nDouble tap to finish.',
                                     textAlign: TextAlign.center,
                                     style: TextStyle(color: Colors.white, shadows: [Shadow(blurRadius: 4, color: Colors.black)]),
                                   ),
                                 ),
                               ),
                           ],
                         ),
                       );
                     },
                   ),
                 ),
               ),

               // ROI List
               Expanded(
                 flex: 1,
                 child: Container(
                   decoration: BoxDecoration(
                     border: Border(left: BorderSide(color: Colors.grey.shade300)),
                     color: Colors.white,
                   ),
                   child: ListView(
                     children: [
                       const Padding(
                         padding: EdgeInsets.all(12.0),
                         child: Text('Regions', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                       ),
                       if (widget.camera.regions.isEmpty)
                         const Padding(
                           padding: EdgeInsets.all(12.0),
                           child: Text('No regions added yet.', style: TextStyle(color: Colors.grey)),
                         ),
                       ...widget.camera.regions.map((region) => Card(
                         margin: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                         elevation: 2,
                         child: ListTile(
                           leading: CircleAvatar(
                             radius: 8,
                             backgroundColor: _getColorForType(region.type),
                           ),
                           title: Text(region.label, style: const TextStyle(fontWeight: FontWeight.w600)),
                           subtitle: Text(region.type.toUpperCase(), style: TextStyle(fontSize: 12, color: Colors.grey[600])),
                           trailing: IconButton(
                             icon: const Icon(Icons.delete, size: 20, color: Colors.red),
                             onPressed: () => _deleteRegion(region.id),
                             tooltip: 'Delete Region',
                           ),
                         ),
                       )),
                     ],
                   ),
                 ),
               ),
            ],
          ),
        ),
      ],
    );
  }

  Color _getColorForType(String type) {
     switch (type.toLowerCase()) {
      case 'road': return Colors.blue;
      case 'garbage': return Colors.green;
      case 'streetlight': return Colors.amber;
      case 'pothole': return Colors.red;
      case 'overflow': return Colors.brown;
      case 'waterleak': return Colors.cyan;
      case 'roadcrack': return Colors.purple;
      default: return Colors.grey;
    }
  }
}
